services:
  - type: web
    name: dynamic-qr-redirector
    runtime: python
    repo: https://github.com/parthmax2/dynamic-qr
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host=0.0.0.0 --port=10000
    envVars:
      - key: PORT
        value: 10000
    plan: free
    region: oregon
